# Generated by Django 3.1.5 on 2021-01-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('SN', models.CharField(max_length=128)),
                ('red', models.CharField(max_length=128)),
                ('green', models.CharField(max_length=128)),
                ('blue', models.CharField(max_length=128)),
            ],
        ),
    ]
