# Generated by Django 3.1.5 on 2021-01-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='green',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='red',
        ),
    ]
