# Generated by Django 3.1.7 on 2021-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLamps1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_1r', models.CharField(db_index=True, max_length=64, verbose_name='pixel_1_red')),
                ('pixel_1g', models.CharField(db_index=True, max_length=64, verbose_name='pixel_1_green')),
                ('pixel_1b', models.CharField(db_index=True, max_length=64, verbose_name='pixel_1_blue')),
            ],
        ),
    ]
