# Generated by Django 3.1.7 on 2021-03-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamps', '0003_auto_20210328_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlamps1',
            name='pixel_1_blue',
            field=models.CharField(max_length=64, verbose_name='pixel_1_blue'),
        ),
        migrations.AlterField(
            model_name='programlamps1',
            name='pixel_1_green',
            field=models.CharField(max_length=64, verbose_name='pixel_1_green'),
        ),
        migrations.AlterField(
            model_name='programlamps1',
            name='pixel_1_red',
            field=models.CharField(max_length=64, verbose_name='pixel_1_red'),
        ),
    ]
