# Generated by Django 3.1.7 on 2021-03-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lamps', '0004_auto_20210329_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlamps1',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_musician', to='lamps.lamps'),
        ),
    ]
